#! usr/bin/bash
read -p "Please enter database name to connect: " dbname

function databaseconnectionselection(){

    options=("Create-Table" "List-all-Tables" "Drop-Table" "Insert-Into-Table" "Select-from-table" "update-table" "Exit")

select opt in "${options[@]}"
do 
case $opt in

"Create-Table") 

source .././createtable

databaseconnectionselection
;;
"List-all-Tables")

    clear
if [ -z "$(ls -A ~/database/database/$dbname)" ]; then
   echo " database is empty ! 
   
   "
else
    echo "Database contains those tables.. 
    
    "
    ls -I "*.md" ~/database/database/$dbname 
fi

databaseconnectionselection
;;
"Drop-Table")
    source ./../droptable
    databaseconnectionselection
;;
"Insert-Into-Table")
    source ./../inserttable
    databaseconnectionselection
;;
"Select-from-table")
echo "Select-from-table"
break ;
;;
"update-table")
echo "updating table"
break ;
;;
"Exit")
echo "Exit"
clear
selection
;;
esac
done
   
}


function connectdb(){

    if [[ -e $dbname ]] ; then
clear
echo "-----------------------------------------------------"
echo "Connected to $dbname database"
echo "-----------------------------------------------------"

databaseconnectionselection

else
echo "-----------------------------------------------------"
echo "database not existed !"
echo "-----------------------------------------------------"
selection
fi
}

connectdb
