#! usr/bin/bash
echo "   
"
dbname=$(zenity --entry --title="Please enter database name to connect:")

function databaseconnectionselection(){

    items=("Create-Table" "List-all-Tables" "Drop-Table" "Insert-Into-Table" "Select-from-table" "update-table" "Exit")

while item=$(zenity --title="$title" --text="$prompt" --list \
               --column="Options" "${items[@]}")
do
    case "$item" in

"Create-Table") 

    source .././createtable

    databaseconnectionselection
;;
"List-all-Tables")

    clear
    if [ -z "$(ls -A ~/database/database/$dbname)" ]; then
       zenity --warning --title="Warning" --text="Database is empty " --no-wrap

    else
x=` ls -I "*.md" ~/database/database/$dbname ` 
zenity --info --title="    Listing" --text="                Tables  

     $x" --no-wrap
    fi

    databaseconnectionselection
;;
"Drop-Table")
    source ./../droptable
    databaseconnectionselection
    
;;
"Insert-Into-Table")
source ./../inserttable
    databaseconnectionselection

;;
"Select-from-table")
source ./../selecttable

    databaseconnectionselection
;;

"update-table" )
source ./../updatetable
databaseconnectionselection

;;
"Exit")
if zenity --question --title="Exit" --text="Are you sure you want to exit?" --no-wrap 
    then
clear
selection
fi
;;
esac
done
   
}


function connectdb(){

    if [[ -e $dbname ]] ; then
clear
zenity --info --title="Done" --text="Connected to $dbname database !" --no-wrap


databaseconnectionselection

else
 zenity --warning --title="Error" --text="Database $dbname not exisetd !" --no-wrap
selection
fi
}

connectdb

