#! usr/bin/bash
read -p "Please enter table name : " tablename

if [[ -e $tablename ]] ; then
    clear
    echo "-----------------------WARNING!!!-----------------"
    echo "-----------------------------------------------------"
    echo "$tablename table already exists !"
    echo "-----------------------------------------------------"

    databaseconnectionselection

elif [[  ! $tablename =~ ^([a-zA-Z\_])+([a-zA-Z0-9\_])*$ ]] ; then
    clear
    echo "-----------------------WARNING!!!-----------------"
    echo "-----------------------------------------------------"
    echo "Please enter a valid name !"
    echo "-----------------------------------------------------"

    databaseconnectionselection

elif [[  ! -e $tablename && $tablename =~ ^([a-zA-Z\_])+([a-zA-Z0-9\_])*$ ]] ; then

    touch  ~/database/database/$dbname/$tablename
    touch  ~/database/database/$dbname/"$tablename.md"

fi
read  -p "Plese enter number of columns : " colnum

while [[ ! $colnum =~ [0-99]+$ ]] ;
    do
    echo "Please enter a valid number !"
    done

for i in $( seq 1 $colnum);
    do
    echo "column number $i ,"
    if (( $i==1 ));
        then echo "Please enter the primary key : "
        read pk
        echo "Please enter the type of key - (string / int ) :"
        read datatype

            echo -n "$pk:" > ~/database/database/$dbname/$tablename
            echo -n "$datatype:" > ~/database/database/$dbname/"$tablename.md"
     else 
        read -p "please enter column name : " colname
        read -p "please enter type of column - (string /int) : "   datatype  
        echo -n "$colname:" >> ~/database/database/$dbname/$tablename
        echo -n "$datatype:" >> ~/database/database/$dbname/"$tablename.md"
        fi
    done 

