#! usr/bin/bash

read -p "Please enter database you want to delete: " drop
if [[ -e $drop ]] ; then
clear
echo "-----------------------------------------------------"
echo "database $drop deleted succesfully !"
echo "-----------------------------------------------------"
echo "                                                      "
echo "                                                      "

rm -r $drop

selection

else
clear
echo "-----------------------------------------------------"
echo "database $drop not existed !"
echo "-----------------------------------------------------"
echo "                                                      "
echo "                                                      "
selection
fi