#! usr/bin/bash
name=$(zenity --entry --title="Enter table name you want to delete")
if [[ -e ~/database/database/$dbname/$name ]] ; then
clear
     zenity --warning --title="Done " --text="Table $name deleted sucessfuly !" --no-wrap

    rm ~/database/database/$dbname/$name
    rm ~/database/database/$dbname/"$name.md"
    databaseconnectionselection

else
clear
     zenity --warning --title="Can not delete " --text="Table $name not existed !" --no-wrap

    databaseconnectionselection
fi
