#! usr/bin/bash

mkdir -p database 
cd database 

function selection(){

    options=("Create-Database" "List-all-Databases" "Drop-Database" "Connect-Database" "Exit")

select opt in "${options[@]}"
do 
case $opt in
"Create-Database") 
echo "database created"
;;
"List-all-Databases")
echo " data base listed"
;;
"Drop-Database")
echo "database deleted"
;;
"Connect-Database")
echo "database connected";;
Exit)
echo "Exit" 
break ;
;;
esac
done
   
}

selection