#! usr/bin/bash

read -p "Please enter table name you want to select from : " seltable

if [[ ! -e ~/database/database/$dbname/$seltable ]] ; then

zenity --warning --title="Warning" --text="Table not existed !" --no-wrap

    databaseconnectionselection


else
clear
echo "-------------------------------------------------------"
sed -n '1!p' ~/database/database/$dbname/$seltable 
echo "-------------------------------------------------------"

fi