#! usr/bin/bash

seltable=$(zenity --entry --title="Please enter table name you want to select from")
if [[ ! -e ~/database/database/$dbname/$seltable ]] ; then

zenity --warning --title="Warning" --text="Table not existed !" --no-wrap

    databaseconnectionselection


else
clear
m=` sed -n '1!p' ~/database/database/$dbname/$seltable ` 
zenity --info --title="View Table" --text="                  $seltable :
 $m" --no-wrap

fi