#! usr/bin/bash
read -p "please enter the table name you want to update " uptablename


if [ ! -e ~/database/database/$dbname/$uptablename ] ; then
    echo "Sorry table not existed !"

else
    read -p "enter value you want to change: " val1
    read -p "enter new value : " val2

sed -n "s/$val1/$val2/gp" ~/database/database/lol/ahly >> ~/database/database/lol/ahly

fi